### ISSUE TITLE
Implement on click show/hide panel?

### ISSUE THREAD

**Issue by ThomasG77** [walkermatt/ol-layerswitcher#123]
Hi,

I've done some hacks to get [a working demo](https://raw.githack.com/ThomasG77/ol-layerswitcher/toggle-panel-onclick/examples/collapse-groups.html) but I'm not happy with the implementation (visible [on branch](https://github.com/ThomasG77/ol-layerswitcher/tree/toggle-panel-onclick))
First, would you be interested by the feature?
If yes, what would be your approach in the code? I'm also thinking about using a distinct icon for fold/unfold the panel.

**Comment by walkermatt** [comment]
Hi,

This has came up a few times now (#39, #99) so yes I think we should add an option to require a close button be activated in order to close the panel.

@StuffOfInterest suggests being consistent with existing controls such as `ol/control/Attribution` which seems sensible.

I personally like the OpenLayers icon for the "open" button (and it can be easily overridden via CSS). I think that another icon would make sense to indicate the panel can be closed.

**Comment by LandonMarshall** [comment]
Is this issue still active? I would benefit from this feature as well. I can open a pull request if neccessary.

**Comment by adrelino** [comment]
@LandonMarshall I just opened a pull request #258. 

@ThomasG77 Regarding the distinct icon I followed `ol/control/Attribution` which lets you set text icons via the options`label` and `collapseLabel`.

Per default, I only set the collapseLabel, which displays `'»'` on top of the button to indicate closing, which is in line with the Attribution control @walkermatt . For opening, they use an `'i'`, but I left it blank for now since we have the openlayers icon as background anyways, which can be disabled via css if wanted as you mentioned.
